# ---------- builder ----------
FROM node:18-bullseye-slim AS builder

WORKDIR /app

COPY package*.json ./

# install ALL deps needed for build
RUN npm ci

COPY . .

ENV NODE_ENV=production

RUN npm run build


# ---------- runner ----------
FROM node:18-bullseye-slim AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000

CMD ["node", "server.js"]