version: '3'
services:
  nextjs-app:
    build: .
    ports:
      - "3001:3000"  # Map host port 3001 to container port 3000
    cpus: "0.5"
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./service:/app/service
      - ./next.config.mjs:/app/next.config.mjs
      - ./jsconfig.json:/app/jsconfig.json
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.js:/app/tailwind.config.js

      - /app/node_modules
    environment:
      NODE_ENV: development  
    command: npm run dev  # Command to start the Next.js app
    